package work.basil.example.exgooglemapsinjavafx;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.scene.Scene;
import javafx.scene.layout.BorderPane;
import javafx.scene.web.WebView;
import javafx.stage.Stage;

import java.io.IOException;

// Example of using the Google Maps website within a JavaFX WebView widget.
// By Basil Bourque, 2025-04.  http://www.Basil.work 🌿·🛠️
// I started with a project created by the IntelliJ template for JavaFX.
// I then modified HelloApplication.java, the Maven POM file, and `module-info.java`.

// This code shows that the WebView widget can be used with the Google Maps website.
// However, be aware that many warnings and `java.lang.NullPointerException` exceptions
// are thrown while using the WebView widget.

//    Copyright (c) 2025 Basil Bourque <pro-bono@basil.work>
//
//    Permission to use, copy, modify, and distribute this software for any
//    purpose with or without fee is hereby granted, provided that the above
//    copyright notice and this permission notice appear in all copies.
//
//    THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
//    WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
//    MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
//    ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
//    WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
//    ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
//    OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.

public class HelloApplication extends Application
{
    @Override
    public void start ( final Stage stage )
    {
        this.startWithoutFxml ( stage );
        // try { this.startWithFxml ( stage ); } catch ( IOException e ) { throw new RuntimeException ( e ); }
    }

    private void startWithoutFxml ( final Stage stage )
    {
        // Widgets
        final WebView webView = new WebView ( );
        webView.getEngine ( ).load ( "https://www.google.com/maps" );

        // Arrange
        BorderPane borderPane = new BorderPane ( );
        borderPane.setCenter ( webView );

        // Window
        stage.setTitle ( "Example Google Maps in JavaFX" );
        stage.setScene ( new Scene ( borderPane , 900 , 600 ) );
        stage.show ( );
    }

    private void startWithFxml ( final Stage stage ) throws IOException
    {
        // This code is preserved from code generated by IntelliJ template for JavaFX.
        // This unedited code does not show the WebView widget.
        FXMLLoader fxmlLoader = new FXMLLoader ( HelloApplication.class.getResource ( "hello-view.fxml" ) );
        Scene scene = new Scene ( fxmlLoader.load ( ) , 320 , 240 );
        stage.setTitle ( "Hello!" );
        stage.setScene ( scene );
        stage.show ( );
    }

    public static void main ( String[] args )
    {
        Application.launch ( );
    }
}


